"""Run every diagnostic and produce ``DIAGNOSTICS_SUMMARY.md``.

Usage::

    python -m diagnostics.run_all

Loads from cache where possible. The fundamentals + price + filing-count
caches must already exist (run ``python main.py`` once first).
"""

from __future__ import annotations

import logging
from pathlib import Path

import pandas as pd

import config
from feature_engine import (
    build_features,
    clean_features as clean_features_fn,
    fetch_filing_counts,
    fetch_fundamentals,
    fetch_prices,
)
from pca_cluster import run_clustering, run_pca
from universe import get_sp600_universe

from .ablation import run_ablation
from .cluster_quality import audit_clusters
from .feature_audit import audit_features, write_audit_summary
from .individual_stock_audit import audit_portfolio
from .stability_test import test_subsample_stability

logger = logging.getLogger(__name__)


def _load_data():
    """Fetch the same inputs main.py uses, leaning on caches."""
    universe_df = get_sp600_universe()
    tickers = sorted(set(universe_df["Ticker"].tolist()) | set(config.PORTFOLIO))
    universe_df = universe_df[universe_df["Ticker"].isin(tickers)].copy()

    # Pad portfolio names that may not be in the current Wikipedia list
    missing = [t for t in config.PORTFOLIO if t not in universe_df["Ticker"].values]
    if missing:
        pad = pd.DataFrame({
            "Ticker": missing, "Company": missing,
            "Sector": "Unknown", "Industry": "Unknown",
        })
        universe_df = pd.concat([universe_df, pad], ignore_index=True)

    prices = fetch_prices(tickers, lookback_days=config.PRICE_LOOKBACK_DAYS)
    bundles = fetch_fundamentals(tickers)

    try:
        filing_counts = fetch_filing_counts(tickers, days=90)
    except Exception as exc:  # noqa: BLE001
        logger.warning("filing counts fetch failed (using empty): %s", exc)
        filing_counts = {}

    return universe_df, prices, bundles, filing_counts


def _write_master_summary(findings: dict, output_dir: Path) -> None:
    """The ``DIAGNOSTICS_SUMMARY.md`` consumers should read first."""
    lines = [
        "# PCA Pipeline Diagnostic Summary",
        "",
        "Generated by `python -m diagnostics.run_all`. Read this first, then "
        "drill into the individual reports referenced below.",
        "",
        "## Top-level verdict",
        "",
    ]
    issues: list[str] = []

    cq = findings.get("cluster_quality", {})
    sizes = cq.get("cluster_size_pcts", {})
    if sizes:
        max_pct = max(sizes.values())
        if max_pct > 50:
            issues.append(
                f"⚠ **Dominant cluster**: {max_pct:.0f}% of universe is in a "
                f"single cluster. K-means is finding one big blob, not "
                f"separated risk strata."
            )
    sil = cq.get("overall_silhouette", 0.0)
    if sil < 0.30:
        issues.append(
            f"⚠ **Weak overall clustering** (silhouette={sil:.3f}). Cluster "
            f"boundaries are poorly defined."
        )

    stab = findings.get("stability", {})
    eig_sims = stab.get("eigenvector_similarity_means", {})
    for pc, sim in eig_sims.items():
        if sim < 0.7:
            issues.append(
                f"⚠ **Unstable {pc}** (cosine similarity {sim:.2f} across "
                f"subsamples). Component meaning shifts with the input universe."
            )
    ari = stab.get("cluster_ari_mean", 1.0)
    if ari < 0.5:
        issues.append(
            f"⚠ **Unstable clustering** (mean ARI {ari:.2f}). Assignments "
            f"shift significantly under random subsampling."
        )

    if not issues:
        lines.append("✓ No structural issues detected. Pipeline appears reliable.")
    else:
        lines.append("**Issues found that must be addressed before deployment:**")
        lines.append("")
        for issue in issues:
            lines.append(f"- {issue}")

    lines.extend([
        "",
        "## Reports generated",
        "",
        "1. `feature_audit.csv` + `feature_audit_summary.txt` — coverage, variance, PC contribution per feature",
        "2. `cluster_quality.txt` + `cluster_k_comparison.csv` — silhouette, separation, k selection",
        "3. `stability_test.txt` — eigenvector + cluster stability under 80% subsampling",
        "4. `individual_audits/` — per-ticker breakdowns (portfolio + MYRG)",
        "5. `ablation_study.csv` + `ablation_study.txt` — leave-one-out + group-only",
        "",
        "## Specific diagnostic for MYRG",
        "",
        "MYRG had a +70% move; check `individual_audits/audit_MYRG.txt`. It should show:",
        "",
        "- High `momentum_30d` percentile (>95th)",
        "- High `volatility_60d` percentile",
        "- Cluster tier should be **High** or **Critical**, not **Low Risk**",
        "",
        "If MYRG appears in Low Risk despite the move, the features are stale or the",
        "standardization is washing out signal — check `LOOKBACK_DAYS` and the price",
        "cache freshness.",
        "",
        "## Recommended next steps",
        "",
    ])
    if any("Dominant cluster" in i for i in issues):
        lines.extend([
            "**Fix the dominant-cluster problem**",
            "",
            "1. Open `feature_audit_summary.txt` — count features tagged `NOT_LOADING`. ",
            "   If most fundamentals are not loading, the PCA is essentially momentum/vol-",
            "   driven and clusters reflect that single dimension.",
            "2. Check `ablation_study.txt`. If `fundamental_only` has very low ARI vs",
            "   baseline but `market_positioning_only` has high ARI, the clusters are",
            "   purely momentum-driven.",
            "3. Either restore real fundamental data (the Piotroski-coverage history is a",
            "   known issue), drop low-loading features, or switch to HDBSCAN/GMM which",
            "   don't force everything into convex blobs.",
            "",
        ])
    if any("Unstable" in i for i in issues):
        lines.extend([
            "**Fix the stability problem**",
            "",
            "1. Re-check feature coverage in `feature_audit.csv`. Low-coverage features",
            "   inject noise that varies by subsample.",
            "2. Consider sparse PCA / robust PCA so a few extreme observations don't",
            "   dominate the eigenvectors.",
            "",
        ])
    lines.extend([
        "**Only proceed to website deployment after the diagnostics here are clean.**",
        "A website that visualizes broken analytics is worse than no website.",
        "",
    ])
    (output_dir / "DIAGNOSTICS_SUMMARY.md").write_text("\n".join(lines))


def main() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%H:%M:%S",
    )
    for noisy in ("yfinance", "urllib3", "matplotlib", "PIL"):
        logging.getLogger(noisy).setLevel(logging.WARNING)

    output_dir = config.OUTPUT_DIR / "diagnostics"
    output_dir.mkdir(parents=True, exist_ok=True)

    logger.info("Loading data (using caches where available)…")
    universe_df, prices, bundles, filing_counts = _load_data()

    logger.info("Building features…")
    raw_feat = build_features(
        universe_df, bundles, prices,
        filing_counts=filing_counts,
    )
    clean_feat, _imputed = clean_features_fn(raw_feat)

    logger.info("Running PCA + clustering…")
    pca_result = run_pca(clean_feat)
    cluster_result = run_clustering(clean_feat, pca_result)

    logger.info("=" * 60)
    logger.info("RUNNING DIAGNOSTICS")
    logger.info("=" * 60)

    findings: dict = {}

    logger.info("[1/5] Feature audit")
    audit_df = audit_features(raw_feat, clean_feat, pca_result, output_dir)
    write_audit_summary(audit_df, output_dir)
    findings["feature_audit"] = "see feature_audit.csv and feature_audit_summary.txt"

    logger.info("[2/5] Cluster quality")
    findings["cluster_quality"] = audit_clusters(pca_result, cluster_result, output_dir)

    logger.info("[3/5] Stability (10 subsample iterations)")
    findings["stability"] = test_subsample_stability(
        clean_feat, pca_result.feature_cols,
        n_components=config.N_PCA_COMPONENTS,
        n_clusters=cluster_result.k,
        n_iterations=10,
        output_dir=output_dir,
    )

    logger.info("[4/5] Individual stock audits (portfolio + MYRG)")
    audit_portfolio(
        list(config.PORTFOLIO.keys()),
        pca_result, clean_feat, cluster_result, raw_feat,
        output_dir, extra_tickers=["MYRG"],
    )
    findings["individual_audits"] = "see individual_audits/"

    logger.info("[5/5] Ablation study")
    run_ablation(
        clean_feat, pca_result.feature_cols,
        n_components=config.N_PCA_COMPONENTS,
        n_clusters=cluster_result.k,
        output_dir=output_dir,
    )
    findings["ablation"] = "see ablation_study.csv"

    _write_master_summary(findings, output_dir)

    logger.info("=" * 60)
    logger.info("DIAGNOSTICS COMPLETE")
    logger.info("Outputs: %s", output_dir)
    logger.info("Read DIAGNOSTICS_SUMMARY.md first.")
    logger.info("=" * 60)


if __name__ == "__main__":
    main()
